uploads = []
outputs = []

[[generated]]
id = "dZldcQ67WfWslKLulxIWj"
uri = "file://client/src/assets/floating-robot.png"
type = "image"
title = "purple floating futuristic cute robot"

[[generated]]
id = "qgd1Qyo4oWmlBxU8dTr70"
uri = "file://client/src/assets/simulated-bot-icon.png"
type = "image"
title = "simulated bot vaulty icon"

[[generated]]
id = "5RGuHSqX0eHug-xZdVbLf"
uri = "file://client/src/assets/vaulty-logo-v.png"
type = "image"
title = "vaulty v modern minimalist logo"

[[generated]]
id = "yD1TN721o6ExDoaLvbH2C"
uri = "file://client/src/assets/floating-astronaut.png"
type = "image"
title = "Floating astronaut black visor"
